version: 2
jobs:
    build:
        docker:
            - image: jumperio/vlab-gcc-arm
        environment:
            ARM_NONE_EABI: /usr
        steps:
            - checkout
            - run:
                name: build
                command: make -C pca10040/blank/armgcc/
            - run:
                name: setup
                command: |
                    mkdir ~/.jumper/
                    echo $VLAB_USER_CONFIG > ~/.jumper/config.json
                    virtualenv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
            - persist_to_workspace:
                root: .
                paths:
                    - pca10040/blank/armgcc/_build
                    - venv
            - store_artifacts:
                path: pca10040/blank/armgcc/_build
    test:
        docker:
            - image: circleci/python:2-stretch
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: setup
                command: source venv/bin/activate
            - run:
                name: test
                command: nosetests --rednose -v test

workflows:
    version: 2
    app-button:
        jobs:
            - build
            - test:
                context: org-global
                requires:
                    - build
