version: 2
jobs:
    build:
        docker:
            - image: circleci/python
        environment:
            ARM_NONE_EABI: /home/circleci/gcc-arm-none-eabi-7-2018-q2-update
        steps:
            - checkout
            - restore_cache:
                key: arm-none-eabi-
            - run:
                working_directory: /home/circleci/
                name: install arm-nonoe-eabi
                command: |
                    if [ ! -d gcc-arm-none-eabi-7-2018-q2-update ]; then
                        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz
                        tar xvf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz
                        rm gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz
                    fi
            - save_cache:
                key: arm-none-eabi-{{ checksum "/home/circleci/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc" }}
                paths:
                    - /home/circleci/gcc-arm-none-eabi-7-2018-q2-update
            - run:
                name: build
                command: make -C pca10040/blank/armgcc/
            - run:
                name: setup
                command: |
                    mkdir ~/.jumper/
                    echo $VLAB_USER_CONFIG > ~/.jumper/config.json
                    virtualenv --python=python2 venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - persist_to_workspace:
                root: .
                paths:
                    - pca10040/blank/armgcc/_build
                    - venv
            - store_artifacts:
                path: pca10040/blank/armgcc/_build
    test:
        docker:
            - image: circleci/python
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: test
                command: |
                    . venv/bin/activate
                    nosetests --rednose -v test

workflows:
    version: 2
    app-button:
        jobs:
            - build:
                context: org-global
            - test:
                context: org-global
                requires:
                    - build
